export const refs = {
  homeGalleryList: document.querySelector('.gallery-list'),
  headerContainer: document.querySelector('.header-container'),
  movieModal: document.querySelector('[data-modal]'),
  movieModalContainer: document.querySelector('.js-modal-wrap'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  modal: document.querySelector('[data-modal]'),
  body: document.querySelector('[data-no-scroll]'),
  searchQuery: document.querySelector('.search-input'),
  searchForm: document.getElementById('search-form'),
  backdrop: document.querySelector('.backdrop'),
  teamModal: document.querySelector('[data-team-modal]'),
  closeTeamModalBtn: document.querySelector('[data-team-modal-close]'),
  teamBackdrop: document.querySelector('.team-backdrop'),
  teamModalBtn: document.querySelector('[data-mod]'),
  closeSignInModal: document.querySelector('.modal-SignIn-close'),
  signInBackdrop: document.querySelector('.signIn'),
  openSignInModal: document.querySelector('.js-signIn'),
  openSignInModalNd: document.querySelector('.signIn-open'),
  openSignUpModal: document.querySelector('.signUp-open'),
  signUpBackdrop: document.querySelector('.signUp'),
  closeSignUpModal: document.querySelector('.modal-signUp-close'),
};
